# docker ps -a
# docker compose -f infra/compose.yaml up -d
# psql --host=localhost --username=postgres --port=5435

services:
  database:
    container_name: "postgres-dev"
    image: "postgres:16.0-alpine3.18"
    env_file:
      - ../.env.development
    ports:
      - "5435:5432"
